////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'onboard_repository.dart';
import 'package:injectable/injectable.dart';
import '../../data/local/onboard_local_datasource.dart';
import '../usecases/is_fresh.dart';
import '../usecases/set_unfresh.dart';
////********** END IMPORTS **********////

@LazySingleton(as: OnboardRepository)
class OnboardRepositoryImp implements OnboardRepository {
////********** START VARIABLES **********////
  final OnboardLocalDataSource _onboardLocalDataSource;
////********** END VARIABLES **********////

  OnboardRepositoryImp({
////********** START RECEIVE VALUES **********////
    required OnboardLocalDataSource onboardLocalDataSource,
////********** END RECEIVE VALUES **********////
  }) :
////********** START SET VALUES **********////
        _onboardLocalDataSource = onboardLocalDataSource
////********** END SET VALUES **********////
  ;

////********** START METHODS **********////
  /// [IsFreshUsecaseInput] is received to [isFresh] method as parameter
  /// [IsFreshUsecaseOutput] is returned from [isFresh] method
  @override
  Future<IsFreshUsecaseOutput> isFresh(IsFreshUsecaseInput input) async {
    return _onboardLocalDataSource.isFresh(input);
  }

  /// [SetUnfreshUsecaseInput] is received to [setUnfresh] method as parameter
  /// [SetUnfreshUsecaseOutput] is returned from [setUnfresh] method
  @override
  Future<SetUnfreshUsecaseOutput> setUnfresh(
      SetUnfreshUsecaseInput input) async {
    return _onboardLocalDataSource.setUnfresh(input);
  }

////********** END METHODS **********////
}
